<a href="https://colab.research.google.com/github/SANMYINTHLAING2215/BDA-PROJECT-3/blob/main/BDA_(Project_3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas
import json

with open("sample_supplies.sales.json", "r") as file:
    data = json.load(file)

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [ ]:
from collections import defaultdict

product_sales = defaultdict(float)

for record in data:
    for item in record['items']:
        product_sales[item['name']] += float(item['price']['$numberDecimal']) * item['quantity']

top_10_products = sorted(product_sales.items(), key=lambda x: x[1], reverse=True)[:10]

unique_products = set(item['name'] for record in data for item in record['items'])
num_unique_products = len(unique_products)

top_10_products, num_unique_products

([('laptop', 6775977.070000009),
  ('backpack', 817374.100000001),
  ('pens', 581843.2699999991),
  ('binder', 511644.5700000008),
  ('notepad', 463615.48000000045),
  ('envelopes', 376658.4900000001),
  ('printer paper', 367459.2900000008)],
 7)

In [ ]:
store_product_sales = defaultdict(lambda: defaultdict(float))

for record in data:
    location = record['storeLocation']
    for item in record['items']:
        store_product_sales[location][item['name']] += float(item['price']['$numberDecimal']) * item['quantity']

top_3_products_by_store = {}
for location, products in store_product_sales.items():
    top_3_products_by_store[location] = sorted(products.items(), key=lambda x: x[1], reverse=True)[:3]

top_3_products_by_store

{'Denver': [('laptop', 1961659.25),
  ('backpack', 245679.34000000005),
  ('pens', 185008.38999999966)],
 'Seattle': [('laptop', 1565138.1500000004),
  ('backpack', 178387.46999999988),
  ('pens', 123445.60999999993)],
 'London': [('laptop', 1073098.7200000007),
  ('backpack', 144529.13999999998),
  ('pens', 92602.29999999993)],
 'Austin': [('laptop', 1018494.0499999992),
  ('backpack', 115217.59),
  ('pens', 74622.51999999997)],
 'New York': [('laptop', 694613.3199999997),
  ('backpack', 82563.13999999998),
  ('pens', 64029.899999999994)],
 'San Diego': [('laptop', 462973.57999999996),
  ('backpack', 50997.42),
  ('pens', 42134.54999999998)]}

In [ ]:
store_sales = defaultdict(float)

for record in data:
    location = record['storeLocation']
    for item in record['items']:
        store_sales[location] += float(item['price']['$numberDecimal']) * item['quantity']

store_rankings = sorted(store_sales.items(), key=lambda x: x[1], reverse=True)
store_rankings

[('Denver', 2921009.9200000027),
 ('Seattle', 2255947.6900000004),
 ('London', 1583066.7900000007),
 ('Austin', 1445603.109999999),
 ('New York', 1016059.5899999982),
 ('San Diego', 672885.1699999996)]

In [ ]:
from collections import defaultdict
import pandas as pd
import json

with open("sample_supplies.sales.json", "r") as file:
    data = json.load(file)

purchase_by_gender = defaultdict(lambda: defaultdict(int))

for record in data:
    gender = record['customer']['gender']
    method = record['purchaseMethod']
    purchase_by_gender[gender][method] += 1

purchase_method_table = {
    "Online": {
        "Male": purchase_by_gender['M']['Online'],
        "Female": purchase_by_gender['F']['Online']
    },
    "In store": {
        "Male": purchase_by_gender['M']['In store'],
        "Female": purchase_by_gender['F']['In store']
    }
}

df = pd.DataFrame(purchase_method_table)
df

        Online  In store
Male       772      1389
Female     813      1430

In [ ]:
from datetime import datetime

monthly_sales = defaultdict(float)

for record in data:
    date = datetime.fromisoformat(record['saleDate']['$date'][:-1])
    month_key = f"{date.year}-{date.month:02}"
    for item in record['items']:
        monthly_sales[month_key] += float(item['price']['$numberDecimal']) * item['quantity']

sorted_monthly_sales = sorted(monthly_sales.items(), key=lambda x: x[0])
sorted_monthly_sales

[('2013-01', 196043.75999999992),
 ('2013-02', 147622.58999999994),
 ('2013-03', 140700.06),
 ('2013-04', 162336.67000000022),
 ('2013-05', 179143.37000000002),
 ('2013-06', 142132.01999999993),
 ('2013-07', 176298.22999999984),
 ('2013-08', 130977.22),
 ('2013-09', 137871.99000000008),
 ('2013-10', 173126.73000000004),
 ('2013-11', 148358.37999999992),
 ('2013-12', 174306.96),
 ('2014-01', 125824.01999999995),
 ('2014-02', 141174.40999999983),
 ('2014-03', 193413.49999999988),
 ('2014-04', 132593.08000000002),
 ('2014-05', 166896.7999999999),
 ('2014-06', 143304.56000000006),
 ('2014-07', 184804.59999999995),
 ('2014-08', 167979.80999999988),
 ('2014-09', 159802.91999999993),
 ('2014-10', 149284.83999999994),
 ('2014-11', 180564.85000000003),
 ('2014-12', 139466.83000000013),
 ('2015-01', 222577.01000000007),
 ('2015-02', 189776.14999999962),
 ('2015-03', 178086.9399999999),
 ('2015-04', 132298.5),
 ('2015-05', 167482.68999999992),
 ('2015-06', 149484.34000000005),
 ('2015-07', 149510.46999999997),
 ('2015-08', 154868.62999999992),
 ('2015-09', 135615.80000000008),
 ('2015-10', 175215.34000000005),
 ('2015-11', 158390.41999999987),
 ('2015-12', 166565.02),
 ('2016-01', 166558.9299999999),
 ('2016-02', 120783.5200000001),
 ('2016-03', 193185.17000000007),
 ('2016-04', 137340.27000000002),
 ('2016-05', 162966.06000000017),
 ('2016-06', 132942.54000000007),
 ('2016-07', 180331.10000000003),
 ('2016-08', 164555.32999999987),
 ('2016-09', 138299.52999999988),
 ('2016-10', 151698.92999999988),
 ('2016-11', 170758.4100000001),
 ('2016-12', 215400.07000000007),
 ('2017-01', 207037.74999999994),
 ('2017-02', 134527.54000000018),
 ('2017-03', 162351.14999999997),
 ('2017-04', 191990.93999999994),
 ('2017-05', 202403.84999999995),
 ('2017-06', 201552.5500000001),
 ('2017-07', 156106.89999999994),
 ('2017-08', 173196.1299999999),
 ('2017-09', 186976.2600000001),
 ('2017-10', 191681.2500000001),
 ('2017-11', 202330.86000000022),
 ('2017-12', 175697.7200000001)]